language: python
sudo: required
dist: trusty
services:
  - docker
before_install:
  - sudo apt-get install -y build-essential
  - cd src
install:
  - travis_wait 60 make all
script:
  - python test.py
