sudo: required
services:
  - docker
before_install:
  - cd src
  - tar xvzf ../data/*.tar.gz -C ../data && mv ../data/rdf/* .
  - docker pull candygene/docker-virtuoso
  - docker run --name abg-ld -v $PWD:/tmp/share -p 8890:8890 -d candygene/docker-virtuoso
  - docker ps -a
install:
  - docker exec abg-ld make all
script:
  - cat virtuoso.log
