language: python
sudo: required
dist: trusty
services:
  - docker
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential
install:
  - cd src && make all
script:
  - test.py
